name: Build EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller `
            --onefile `
            --icon=icon.ico `
            --add-data "topics.json;." `
            main_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: dist/main_gui.exe
